import type React from "react"
import type { Metadata, Viewport } from "next"
import { Cairo, Inter } from "next/font/google"
import "./globals.css"
import AnimatedBackground from "@/components/animated-background"
import ClientComponents from "@/components/client-components"
import ThemeToggle from "@/components/theme-toggle"
import AccessibilityMenu from "@/components/accessibility-menu"
import PerformanceMonitor from "@/components/performance-monitor"
import SmartNotifications from "@/components/smart-notifications"
import SiteHeader from "@/components/site-header"
import Footer from "@/components/footer"
import { generateMetaKeywords } from "@/lib/seo-keywords"
import Script from "next/script"

const cairo = Cairo({
  subsets: ["arabic", "latin"],
  display: "swap",
  variable: "--font-cairo",
})

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
})

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 5,
  userScalable: true,
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#ffffff" },
    { media: "(prefers-color-scheme: dark)", color: "#0a0a0a" },
  ],
}

export const metadata: Metadata = {
  metadataBase: new URL("https://ehabgm.com"),
  title: {
    default: "ehabgm | إيهاب جى ام - مصمم مواقع ومتاجر إلكترونية | Freelance Web & Graphic Designer",
    template: "%s | ehabgm - إيهاب جرافيك",
  },
  description:
    "ehabgm - إيهاب جى ام | مصمم مواقع ومتاجر إلكترونية محترف | مصمم جرافيك مستقل | خبير إعلانات ممولة وتسويق رقمي | Professional Freelance Web Designer, Graphic Designer & Digital Marketing Expert in Egypt. تصميم مواقع، متاجر، شعارات، هوية بصرية، إدارة سوشيال ميديا. اتصل: 01022679250",
  keywords: generateMetaKeywords().split(", "),
  authors: [
    { name: "إيهاب محمد", url: "https://ehabgm.com" },
    { name: "ايهاب جى ام", url: "https://ehabgm.com" },
    { name: "ehabgm", url: "https://ehabgm.com" },
    { name: "Ehab Mohamed Designer", url: "https://ehabgm.com" },
    { name: "إيهاب محمد مصمم جرافيك", url: "https://ehabgm.com" },
    { name: "Ehab Mohamed Marketing", url: "https://ehabgm.com" },
    { name: "المصمم إيهاب محمد", url: "https://ehabgm.com" },
    { name: "Ehab GM Studio", url: "https://ehabgm.com" },
    { name: "إيهاب محمد لتطوير الأعمال", url: "https://ehabgm.com" },
    { name: "Ehabgm Online Services", url: "https://ehabgm.com" },
    { name: "مصمم شعار احترافي", url: "https://ehabgm.com" },
    { name: "مصمم لوجو مودرن", url: "https://ehabgm.com" },
    { name: "صناعة هوية بصرية كاملة", url: "https://ehabgm.com" },
    { name: "مصمم علامة تجارية مميزة", url: "https://ehabgm.com" },
    { name: "لوجو جاهز للتحميل", url: "https://ehabgm.com" },
    { name: "تصميم شعار بالخط العربي الحر", url: "https://ehabgm.com" },
    { name: "شعار كوفي احترافي", url: "https://ehabgm.com" },
    { name: "تصميم شعار ديواني", url: "https://ehabgm.com" },
    { name: "تصميم شعار ثلث", url: "https://ehabgm.com" },
    { name: "لوجو شركات عقارية", url: "https://ehabgm.com" },
    { name: "تصميم شعار مطاعم وكافيهات", url: "https://ehabgm.com" },
    { name: "لوجو كوفي شوب", url: "https://ehabgm.com" },
    { name: "تصميم شعار عيادات", url: "https://ehabgm.com" },
    { name: "لوجو مستشفيات وصيدليات", url: "https://ehabgm.com" },
    { name: "تصميم شعار مدارس وجامعات", url: "https://ehabgm.com" },
    { name: "لوجو مكاتب محاماة", url: "https://ehabgm.com" },
    { name: "تصميم شعار صالونات تجميل", url: "https://ehabgm.com" },
    { name: "لوجو مراكز سبا", url: "https://ehabgm.com" },
    { name: "تصميم شعار جيم ورياضة", url: "https://ehabgm.com" },
    { name: "لوجو ملابس وأزياء", url: "https://ehabgm.com" },
    { name: "تصميم شعار شفاف PNG", url: "https://ehabgm.com" },
    { name: "زيادة مبيعات متجر سلة وزد", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة استشارات هندسية", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لمصنع ملابس", url: "https://ehabgm.com" },
    { name: "عمل فيديو وايت بورد انيميشن", url: "https://ehabgm.com" },
    { name: "تصميم فيديو ترويجي للتطبيقات", url: "https://ehabgm.com" },
    { name: "لوجو تطبيق توصيل طلبات", url: "https://ehabgm.com" },
    { name: "تصميم واجهة مستخدم UI UX ", url: "https://ehabgm.com" },
    { name: "تصميم ايقونات تطبيقات احترافية", url: "https://ehabgm.com" },
    { name: "خبير سيو SEO للمواقع العربية", url: "https://ehabgm.com" },
    { name: "تصميم بروفايل انستجرام جذاب", url: "https://ehabgm.com" },
    { name: "ادارة حملات جوجل ديسبلي Google Display", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة تنظيف ومكافحة حشرات", url: "https://ehabgm.com" },
    { name: "عمل لوجو لقناة العاب جيمنج", url: "https://ehabgm.com" },
    { name: "تصميم غلاف صفحة فيسبوك احترافي", url: "https://ehabgm.com" },
    { name: "تصميم خلفيات جوال 4K", url: "https://ehabgm.com" },
    { name: "تصميم شعار صيدلية مودرن", url: "https://ehabgm.com" },
    { name: "تحميل صور 3D بدون حقوق", url: "https://ehabgm.com" },
    { name: "تصميم كتيبات ومنشورات طبية", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة شحن دولي", url: "https://ehabgm.com" },
    { name: "تصميم شعار لمركز تدريب وكورسات", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة امن وحراسة", url: "https://ehabgm.com" },
    { name: "تصميم علب العطور الفاخرة", url: "https://ehabgm.com" },
    { name: "تصميم شنط ورقية للمحلات", url: "https://ehabgm.com" },
    { name: "تجهيز ملفات الطباعة والوان CMYK", url: "https://ehabgm.com" },
    { name: "خبير اعلانات لينكد ان LinkedIn Ads", url: "https://ehabgm.com" },
    { name: "زيادة زوار المتاجر الالكترونية", url: "https://ehabgm.com" },
    { name: "تصميم منيو مطاعم كتروني QR Code", url: "https://ehabgm.com" },
    { name: "تصميم واجهة متجر شوبيفاي احترافية", url: "https://ehabgm.com" },
    { name: "ربط الدومين مع شوبيفاي وسلة", url: "https://ehabgm.com" },
    { name: "تصميم لوجو ذهبي فاخر للعقارات", url: "https://ehabgm.com" },
    { name: "عمل فيديو موشن جرافيك 60 ثانية", url: "https://ehabgm.com" },
    { name: "تصميم شعار شركة استيراد وتصدير", url: "https://ehabgm.com" },
    { name: "تصميم بوسترات افلام ومسلسلات", url: "https://ehabgm.com" },
    { name: "خدمة تحويل الصور الى ناقلات Vector", url: "https://ehabgm.com" },
    { name: "تصميم غلاف مجلة احترافي", url: "https://ehabgm.com" },
    { name: "تصميم تقارير سنوية للشركات", url: "https://ehabgm.com" },
    { name: "عمل هوية بصرية لمحل حلويات", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة تركيب كاميرات مراقبة", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة ترجمة فورية", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة تنظيم مؤتمرات", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة اضاءة وانوار", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة ادوات منزلية", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة لعب اطفال", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة ملابس اطفال", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة مستلزمات طبية", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة اجهزة طبية", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة معامل تحاليل", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة مراكز اشعة", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة رعاية منزلية", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة تمريض منزلي", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة اسعاف خاص", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة دفن الموتى", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة خدمات فندقية", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة سياحة دينية", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة حج وعمرة", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة طيران", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة حجز فنادق", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة تأجير شقق", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة تسويق عقاري", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة تطوير عقاري", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة ادارة املاك", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة تقييم عقاري", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة تمويل عقاري", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة بنوك ومصارف", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة وساطة مالية", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة بورصة واسهم", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة محافظ الكترونية", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة دفع الكتروني", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة تداول عملات", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة تعدين", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة طاقة متجددة", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة غاز طبيعي", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة كهرباء", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة مياه وصرف", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة اعادة تدوير", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة حماية البيئة", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة زراعة وتشجير", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة انتاج حيواني", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة انتاج داجني", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة انتاج سمكي", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة استصلاح اراضي", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة تجارة حبوب", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة استيراد فواكه", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة تصدير خضروات", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة مواد غذائية مجمدة", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة عصائر ومشروبات", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة مياه معدنية", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة سناكس ومقرمشات", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة شيبسي وكراتيه", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة بسكويت وحلويات", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة شيكولاتة", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة قهوة وشاي", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة عطارة وتوابل", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة زيوت وسمن", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة مكرونة ودقيق", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة ارز وبقوليات", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة لحوم ومصنعاتها", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة دواجن ومجمدات", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة اسماك وسي فود", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة منتجات البان", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة جبن وزبادي", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة بيض ومزارع", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة مخبوزات وافران", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة كيك وتورتة", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة ايس كريم", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة وجبات سريعة", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة كبسة ومندي", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة مشويات وكباب", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة شاورما وفطائر", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة بيتزا ومعجنات", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة برجر وسندوتشات", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة طعام صحي دايت", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة تجهيز حفلات طعام", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة بوفيه مفتوح", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة عربات طعام متنقلة", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة كافيهات ومقاهي", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة تحميص بن", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة مستلزمات كافيهات", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة بيع ماكينات قهوة", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة اكواب ورقية", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة مناديل وورقيات", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة منظفات منزلية", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة مساحيق غسيل", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة معطرات جو", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة مستحضرات تجميل", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة شامبو وصابون", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة كريمات وبشرة", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة عطور وبخور", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة هدايا وتحف", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة ورد وزهور", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة تغليف هدايا", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة العاب نارية", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة افراح ومناسبات", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة تصوير فوتوغرافي", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة استوديو فيديو", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة انتاج سينمائي", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة توزيع افلام", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة قنوات فضائية", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة راديو واف ام", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة بودكاست", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة صحافة واعلام", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة جرايد ومجلات", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة نشر وتوزيع", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة مطابع ودعاية", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة لوحات اعلانية", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة هدايا دعائية", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة تنظيم معارض", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة مؤتمرات وندوات", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة تدريب مهني", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة تعليم لغات", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة دروس خصوصية", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة كورسات اون لاين", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة منصات تعليمية", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة مدارس دولية", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة حضانات اطفال", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة العاب ذكاء", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة قصص اطفال", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة رسوم متحركة", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة العاب فيديو", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة تطبيقات موبايل", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة مواقع الكترونية", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة استضافة مواقع", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة امن معلومات", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة شبكات واتصالات", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة كمبيوتر ولابتوب", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة صيانة حاسب", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة برمجيات جاهزة", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة انظمة محاسبية", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة نقاط بيع POS", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة كاميرات مراقبة", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة اجهزة انذار", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة بوابات الكترونية", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة سمارت هوم", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة اضاءة حديثة", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة تكييف وتبريد", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة غسالات وثلاجات", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة بوتاجازات وافران", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة فلاتر ومنقيات مياه", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة سخانات وطاقة", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة خلاطات وادوات مطبخ", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة مفروشات واقمشة", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة سجاد وموكيت", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة مراتب ومخدات", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة نجف وكريستال", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة زجاج ومرايا", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة رخام وجرانيت", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة سيراميك وبورسلين", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة دهانات واصباغ", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة جبس بورد", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة ورق حائط", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة ارضيات باركيه", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة ابواب وشبابيك", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة الوميتال يو بي في سي", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة حدادة وكريتال", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة نجارة واثاث", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة مطابخ خشب والومنيوم", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة غرف نوم واطفال", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة انتريهات وصالونات", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة مكاتب وكراسي", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة تجهيز مكاتب", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة تجهيز محلات", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة تجهيز فنادق", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة تجهيز مستشفيات", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة تجهيز مطاعم", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة تجهيز سوبر ماركت", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة ثلاجات عرض", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة ارفف وتخزين", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة ونش ورافعات", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة نقل ثقيل", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة لودر وحفار", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة مولدات كهرباء", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة طلمبات مياه", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة ضواغط هواء", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة ماكينات تصنيع", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة خطوط انتاج", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة صيانة مصانع", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة توريدات عمومية", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة مقاولات عامة", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة استثمار سياحي", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة تطوير زراعي", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة انتاج فني", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة تسويق رياضي", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة رعاية لاعبين", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة اكاديمية كرة قدم", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة نادي صحي", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة مكملات غذائية", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة ملابس رياضية", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة احذية رياضية", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة اجهزة رياضية", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة حمامات سباحة", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة تنسيق حدائق", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة شلالات ونوافير", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة مشايات وبرجولات", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة نجيل صناعي", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة ملاعب بادل", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة تأجير ملاعب", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة سباق سيارات", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة صيد ورحلات", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة معدات غوص", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة يخوت ومراكب", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة شحن بحري", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة تخليص جمركي", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة نقل بري", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة شحن جوي", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة بريد سريع", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة خدمات لوجستية", url: "https://ehabgm.com" },
    { name: "تصميم هوية بصرية لشركة سلاسل امداد", url: "https://ehabgm.com" },
    { name: "تصميم لوجو لشركة مخازن ومستودعات", url: "https://ehabgm.com" },
    { name: "عمل لوجو لشركة امن ونظافة", url: "https://ehabgm.com" },
    { name: "تصميم شعار لشركة صيانة وتشغيل", url: "https://ehabgm.com" },
    { name: "موقع ايهاب محمد للتصميم الجرافيكي 2025", url: "https://ehabgm.com" },
    { name: "إيهاب محمد", url: "https://ehabgm.com" },
    { name: "ايهاب جى ام", url: "https://ehabgm.com" },
    { name: "ehabgm", url: "https://ehabgm.com" },
    { name: "إيهاب مصمم جرافيك", url: "https://ehabgm.com" },
    { name: "Ehab Mohamed Graphic Designer", url: "https://ehabgm.com" },
    { name: "Ehab GM Design", url: "https://ehabgm.com" },
    { name: "إنشاء متاجر شوبيفاي Shopify", url: "https://ehabgm.com" },
    { name: "تصميم مواقع ووردبريس WordPress", url: "https://ehabgm.com" },
    { name: "إنشاء متجر إلكتروني احترافي", url: "https://ehabgm.com" },
    { name: "تصميم متجر سلة وزد", url: "https://ehabgm.com" },
    { name: "تجهيز براند تجاري كامل", url: "https://ehabgm.com" },
    { name: "إدارة إعلانات ممولة", url: "https://ehabgm.com" },
    { name: "خبير تسويق إلكتروني", url: "https://ehabgm.com" },
    { name: "إعلانات فيسبوك وانستجرام", url: "https://ehabgm.com" },
    { name: "إعلانات جوجل ادز Google Ads", url: "https://ehabgm.com" },
    { name: "تسويق عبر تيك توك وسناب شات", url: "https://ehabgm.com" },
    { name: "حملات إعلانية لزيادة المبيعات", url: "https://ehabgm.com" },
    { name: "Logo Maker Arabic", url: "https://ehabgm.com" },
    { name: "Huawei Ehab Group Solutions", url: "https://ehabgm.com/custom-solutions" },
    { name: "Samsung Ehab Group Integration", url: "https://ehabgm.com/custom-solutions" },
    { name: "متجر سبيشلتي هاب", url: "https://ehabgm.com/ecommerce" },
    { name: "ايهاب فون", url: "https://ehabgm.com" },
    { name: "إيهاب سنتر المنتجات", url: "https://ehabgm.com/portfolio" },
    { name: "موقع ايهاب", url: "https://ehabgm.com" },
    { name: "Ehab Center Online", url: "https://ehabgm.com" },
  ],
  creator: "إيهاب محمد - Ehab Mohamed",
  publisher: "ehabgm",
  robots: {
    index: true,
    follow: true,
    nocache: false,
    googleBot: {
      index: true,
      follow: true,
      "max-video-preview": -1,
      "max-image-preview": "large",
      "max-snippet": -1,
    },
  },
  icons: {
    icon: [
      { url: "https://i.postimg.cc/TYyK2Rtv/logo.png", sizes: "32x32", type: "image/png" },
      { url: "https://i.postimg.cc/TYyK2Rtv/logo.png", sizes: "16x16", type: "image/png" },
    ],
    apple: [{ url: "https://i.postimg.cc/TYyK2Rtv/logo.png", sizes: "180x180", type: "image/png" }],
    shortcut: "https://i.postimg.cc/TYyK2Rtv/logo.png",
  },
  openGraph: {
    title: "ehabgm | إيهاب جرافيك - مصمم مواقع ومتاجر | Freelance Web Designer",
    description:
      "مصمم مواقع ومتاجر إلكترونية محترف | مصمم جرافيك مستقل | خبير تسويق رقمي وإعلانات ممولة | Professional Freelance Web & Graphic Designer",
    url: "https://ehabgm.com",
    siteName: "ehabgm - إيهاب جرافيك",
    locale: "ar_EG",
    alternateLocale: ["en_US", "en_GB"],
    type: "website",
    images: [
      {
        url: "https://i.postimg.cc/TYyK2Rtv/logo.png",
        width: 1200,
        height: 630,
        alt: "ehabgm - إيهاب جرافيك | مصمم مواقع ومتاجر",
        type: "image/png",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: "ehabgm | إيهاب جرافيك - Freelance Designer",
    description: "مصمم مواقع ومتاجر | مصمم جرافيك | خبير تسويق رقمي | Web & Graphic Designer",
    images: ["https://i.postimg.cc/TYyK2Rtv/logo.png"],
    creator: "@ehabgm",
    site: "@ehabgm",
  },
  alternates: {
    canonical: "https://ehabgm.com",
    languages: {
      "ar-EG": "https://ehabgm.com",
      "en-US": "https://ehabgm.com/en",
      "x-default": "https://ehabgm.com",
    },
  },
  verification: {
    google: "google-site-verification-code",
  },
  category: "technology",
  classification: "Business, Web Design, Graphic Design, Digital Marketing",
  other: {
    "google-adsense-account": "ca-pub-4442626272315276",
    "msvalidate.01": "bing-verification-code",
    "apple-mobile-web-app-capable": "yes",
    "apple-mobile-web-app-status-bar-style": "default",
    "format-detection": "telephone=yes",
    "mobile-web-app-capable": "yes",
  },
  generator: 'v0.app'
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="ar" dir="rtl" className={`${cairo.variable} ${inter.variable} antialiased`} suppressHydrationWarning>
      <head>
        <Script
          strategy="afterInteractive"
          src="https://www.googletagmanager.com/gtag/js?id=AW-972066349"
        />
        <Script id="google-analytics-combined" strategy="afterInteractive">
          {`
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'AW-972066349');
        gtag('config', 'G-MPG7Z0W6FR');
        gtag('config', 'G-BMV5LLYSZ8');
      `}
        </Script>
        <meta name="google-adsense-account" content="ca-pub-4442626272315276" />
        <meta name="geo.region" content="EG-C" />
        <meta name="geo.placename" content="Helwan, Cairo, Egypt" />
        <meta name="geo.position" content="29.8500;31.3333" />
        <meta name="ICBM" content="29.8500, 31.3333" />
        <meta name="author" content="إيهاب محمد - Ehab Mohamed - ehabgm" />
        <meta name="copyright" content="ehabgm - إيهاب جى إم" />
        <meta name="rating" content="general" />
        <meta name="distribution" content="global" />
        <meta name="revisit-after" content="3 days" />
        <meta httpEquiv="content-language" content="ar, en" />
        <meta name="subject" content="Web Design, Graphic Design, Digital Marketing, ehabgm" />
        <meta name="abstract" content="ehabgm - Professional Freelance Web Designer and Graphic Designer" />
        <meta name="topic" content="Web Design, Graphic Design, E-commerce, Digital Marketing" />
        <meta name="summary" content="مصمم مواقع ومتاجر إلكترونية محترف - Professional Web & Graphic Designer" />
        <meta name="Classification" content="Business/Web Design/Graphic Design/Digital Marketing/Freelance Services" />
        <meta name="designer" content="ehabgm - إيهاب جرافيك" />
        <meta name="owner" content="ehabgm - Ehab Mohamed" />
        <meta name="url" content="https://ehabgm.com" />
        <meta name="identifier-URL" content="https://ehabgm.com" />
        <meta name="directory" content="submission" />
        <meta name="pagename" content="ehabgm - إيهاب جى إم | مصمم مواقع ومتاجر" />
        <meta name="coverage" content="Worldwide" />
        <meta name="target" content="all" />
        <meta name="HandheldFriendly" content="True" />
        <meta name="MobileOptimized" content="320" />
        {/* Alternate language links */}
        <link rel="alternate" hrefLang="ar" href="https://ehabgm.com" />
        <link rel="alternate" hrefLang="en" href="https://ehabgm.com/en" />
        <link rel="alternate" hrefLang="x-default" href="https://ehabgm.com" />
        <link rel="icon" type="image/png" sizes="32x32" href="https://i.postimg.cc/TYyK2Rtv/logo.png" />
        <link rel="icon" type="image/png" sizes="16x16" href="https://i.postimg.cc/TYyK2Rtv/logo.png" />
        <link rel="apple-touch-icon" sizes="180x180" href="https://i.postimg.cc/TYyK2Rtv/logo.png" />
        <link rel="shortcut icon" href="https://i.postimg.cc/TYyK2Rtv/logo.png" />
        <link rel="canonical" href="https://ehabgm.com" />
        <script
          async
          src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client=ca-pub-4442626272315276"
          crossOrigin="anonymous"
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "LocalBusiness",
              "@id": "https://ehabgm.com/#organization",
              name: "ehabgm - إيهاب جى ام",
              alternateName: [
                "ehabgm",
                "إيهاب جى ام",
                "ايهاب جرافيك",
                "Ehab Graphic",
                "إيهاب مصمم الجرافيك ",
                "ايهاب المصمم",
                "Ehab Designer",
                "إيهاب أونلاين",
                "ايهاب حلوان",
                "Ehab Online",
                "إيهاب للتسويق الرقمي",
                "ehabgm Digital Marketing",
                "مصمم مواقع فى مصر",
                "مصمم جرافيك فى حلوان",
                "إيهاب اعلانات ",
                "ايهاب محمد جرافيك",
                "إيهاب جي ام",
                "ايهاب البوب",
                "Ehab GM",
                "ehabgm design",
                "helwan",
                "ehabgm marketing",
                "مصمم شعارات محترف",
                "تصميم لوجو احترافي",
                "صناعة هوية بصرية",
                "مصمم براندات",
                "تصميم علامة تجارية",
                "أفضل مصمم جرافيك",
                "ارخص تصميم لوجو",
                "تصميم شعار شركات",
                "لوجو مطاعم",
                "لوجو كافيهات",
                "تصميم هوية كاملة",
                "مصمم لوجو 3D",
                "تصميم شعار ثنائي الابعاد",
                "تصميم شعار ثلاثي الابعاد",
                "خط عربي احترافي",
                "كليجرافي لوجو",
                "تصميم بزنس كارد",
                "تصميم بروفايل شركات",
                "تصميم منيو مطاعم",
                "تصميم فلاير",
                "تصميم بروشور",
                "تصميم لوحات اعلانية",
                "تصميم بوستات سوشيال ميديا",
                "تصميم غلاف فيسبوك",
                "تصميم صور انستجرام",
                "تصميم بنرات سناب شات",
                "تصميم اعلانات تيك توك",
                "مصمم فيديوهات ريلز",
                "مونتاج فيديو احترافي",
                "موشن جرافيك ديزاين",
                "مصمم 3D محترف",
                "نمذجة ثلاثية الأبعاد",
                "3D Modeling Expert",
                "تصميم ملفات STL",
                "تصميم طباعة 3D",
                "رسم هندسي 3D",
                "تصميم واجهات 3D",
                "مصمم اوتوكاد 3D",
                "3D Studio Max Designer",
                "ريندر احترافي 3D",
                "تصميم منتجات 3D",
                "تصميم مجسمات 3D",
                "تحويل الصور لـ 3D",
                "تصميم شخصيات 3D",
                "خبير تسويق الكتروني",
                "مدير حملات اعلانية",
                "اعلانات فيسبوك ممولة",
                "اعلانات انستجرام ممولة",
                "خبير اعلانات جوجل",
                "Google Ads Expert",
                "اعلانات سناب شات ممولة",
                "اعلانات تيك توك ممولة",
                "زيادة مبيعات المتاجر",
                "خبير سيو SEO",
                "تحسين محركات البحث",
                "خبير SEO يوتيوب",
                "تصدر نتائج البحث",
                "ادارة صفحات السوشيال ميديا",
                "كاتب محتوى اعلاني",
                "كتابة سكريبت فيديو",
                "خبير بيكسل فيسبوك",
                "تتبع الحملات الاعلانية",
                "تحليل بيانات التسويق",
                "انشاء متجر شوبيفاي",
                "Shopify Expert Egypt",
                "تصميم مواقع ووردبريس",
                "WordPress Developer",
                "تجهيز متجر سلة",
                "تجهيز متجر زد",
                "تطوير متاجر الكترونية",
                "تصميم صفحات هبوط",
                "Landing Page Designer",
                "خبير UI UX",
                "تصميم واجهات تطبيقات",
                "تحسين سرعة المواقع",
                "حماية مواقع ووردبريس",
                "تصميم موقع تعريفي",
                "تسويق عقاري احترافي",
                "تصميم شعارات عقارات",
                "تسويق عيادات ومستشفيات",
                "براندينج محاماة",
                "لوجو مكاتب استشارية",
                "تسويق شركات شحن",
                "تصميم تغليف منتجات",
                "Packaging Design Expert",
                "تصميم علب كرتون",
                "تصميم اكياس محلات",
                "تصميم تيشيرتات",
                "لوجو جيم ورياضة",
                "لوجو صالون تجميل",
                "لوجو معمل تحاليل",
                "لوجو صيدلية",
                "لوجو مدرسة",
                "لوجو جامعة",
                "لوجو قناة يوتيوب",
                "تصميم صور مصغرة",
                "YouTube Thumbnail Maker",
                "تصميم انترو فيديو",
                "Logo Animation Expert",
                "تحويل اللوجو لـ 3D",
                "تصميم كروت افراح",
                "تصميم شهادات تقدير",
                "رسم فيكتور ارت",
                "Vector Illustration",
                "تصميم انفوجرافيك",
                "تصميم بوسترات افلام",
                "تصميم مجلات",
                "تصميم كتب واغلفة",
                "تنسيق ملفات PDF",
                "خبير ووردبريس العرب",
                "تصميم متجر دروبشيبينغ",
                "Dropshipping Specialist",
                "ربط بوابات الدفع",
                "زيادة زوار الموقع",
                "خبير اعلانات تويتر",
                "X Ads Marketing",
                "اعلانات لينكد ان",
                "LinkedIn Marketing Expert",
                "تصميم بروفايل انستجرام",
                "تنسيق حسابات السوشيال",
                "خبير تجارة الكترونية",
                "تحسين معدل التحويل",
                "Conversion Rate Optimization",
                "تصميم ايميلات تسويقية",
                "Email Marketing Expert",
                "تصميم بنرات مواقع",
                "Web Banners Design",
                "تصميم ايقونات تطبيقات",
                "App Icon Design",
                "رسم خرائط ذهنية",
                "تصميم عروض بوربوينت",
                "PowerPoint Design Expert",
                "تصميم سيرة ذاتية CV",
                "Professional CV Design",
                "تصميم ملف انجاز",
                "Portfolio Creation",
                "ايهاب جي ام سيو",
                "ايهاب جي ام جرافيك",
                "ايهاب جي ام ماركتنج",
                "إيهاب محمد ديزاينر",
                "Ehab Mohamed Pro",
                "وكالة إيهاب الإبداعية",
                "Ehab Creative Agency",
                "حلول إيهاب الرقمية",
                "Ehab Digital Solutions",
                "تصميم لوجو ذهبي",
                "تصميم شعار بسيط",
                "تصميم لوجو خط كوفي",
                "تصميم شعار خط ثلث",
                "تصميم شعار خط ديواني",
                "لوجو شركات مقاولات",
                "لوجو شركات سياحة",
                "لوجو شركات بترول",
                "لوجو شركات برمجيات",
                "لوجو تطبيقات جوال",
                "تصميم واجهة متجر سلة",
                "تصميم ثيمات ووردبريس",
                "تعديل قوالب شوبيفاي",
                "تصميم متجر نون",
                "تسويق منتجات امازون",
                "خبير امازون FBA",
                "تصميم صور المنتجات",
              ],
              description:
                "ehabgm - إيهاب جرافيك | مصمم مواقع ومتاجر إلكترونية محترف | مصمم جرافيك مستقل | خبير إعلانات ممولة وتسويق رقمي في مصر والوطن العربي | Professional Freelance Web Designer, Graphic Designer & Digital Marketing Expert",
              url: "https://ehabgm.com",
              telephone: "+201022679250",
              email: "info@ehabgm.com",
              image: {
                "@type": "ImageObject",
                url: "https://i.postimg.cc/TYyK2Rtv/logo.png",
                width: 512,
                height: 512,
              },
              logo: {
                "@type": "ImageObject",
                url: "https://i.postimg.cc/TYyK2Rtv/logo.png",
                width: 512,
                height: 512,
              },
              priceRange: "$$",
              aggregateRating: {
                "@type": "AggregateRating",
                ratingValue: "4.9",
                reviewCount: "150",
                bestRating: "5",
                worstRating: "1",
              },
              founder: {
                "@type": "Person",
                name: "إيهاب محمد",
                alternateName: ["Ehab Mohamed", "ايهاب محمد", "Ehab", "إيهاب"],
                jobTitle: "المؤسس والمدير التنفيذي - Founder & CEO",
                url: "https://ehabgm.com/about",
                knowsAbout: [
                  "Web Design",
                  "Graphic Design",
                  "Digital Marketing",
                  "SEO",
                  "Social Media Marketing",
                  "Paid Advertising",
                  "تصميم المواقع",
                  "تصميم الجرافيك",
                  "التسويق الرقمي",
                ],
              },
              address: {
                "@type": "PostalAddress",
                streetAddress: "18,حلوان - Helwan",
                addressLocality: "Cairo",
                addressRegion: "Cairo Governorate",
                postalCode: "11619",
                addressCountry: "EG",
              },
              geo: {
                "@type": "GeoCoordinates",
                latitude: 29.85,
                longitude: 31.3333,
              },
              openingHoursSpecification: [
                {
                  "@type": "OpeningHoursSpecification",
                  dayOfWeek: ["Saturday", "Sunday", "Monday", "Tuesday", "Wednesday", "Thursday"],
                  opens: "09:00",
                  closes: "22:00",
                },
              ],
              sameAs: [
                "https://wa.me/201022679250",
                "https://facebook.com/ehab.gm1",
                "https://instagram.com/ehab.gm1",
                "https://x.com/ehabgm0",
                "https://linkedin.com/company/ehabgm",
                "https://youtube.com/@ehabgm",
                "https://tiktok.com/@ehabgm0",
              ],
              serviceArea: [
                { "@type": "Country", name: "Egypt" },
                { "@type": "Country", name: "Saudi Arabia" },
                { "@type": "Country", name: "United Arab Emirates" },
                { "@type": "Country", name: "Kuwait" },
                { "@type": "Country", name: "Qatar" },
                { "@type": "Country", name: "Bahrain" },
                { "@type": "Country", name: "Oman" },
                { "@type": "Country", name: "Jordan" },
                { "@type": "Country", name: "Lebanon" },
              ],
              knowsAbout: [
                "تصميم مواقع",
                "تصميم متاجر إلكترونية",
                "تصميم جرافيك",
                "تصميم شعارات",
                "تصميم هوية بصرية",
                "إعلانات ممولة",
                "تسويق رقمي",
                "سوشيال ميديا",
                "تحسين محركات البحث",
                "Web Design",
                "E-commerce Design",
                "Graphic Design",
                "Logo Design",
                "Brand Identity",
                "Paid Advertising",
                "Digital Marketing",
                "Social Media Marketing",
                "SEO",
                "تصميم مواقع",
                "تصميم متاجر إلكترونية",
                "تصميم جرافيك",
                "تصميم شعارات",
                "تصميم هوية بصرية",
                "إعلانات ممولة",
                "تسويق رقمي",
                "سوشيال ميديا",
                "تحسين محركات البحث",
                "Web Design",
                "E-commerce Design",
                "Graphic Design",
                "Logo Design",
                "Brand Identity",
                "Paid Advertising",
                "Digital Marketing",
                "Social Media Marketing",
                "SEO",
                "تصميم ثلاثي الأبعاد",
                "3D Modeling",
                "تصميم تجربة المستخدم",
                "UI/UX Design",
                "تطوير المواقع",
                "Web Development",
                "برمجة المتاجر",
                "Shopify Development",
                "WordPress Development",
                "تطوير ووردبريس",
                "برمجة تطبيقات الجوال",
                "Mobile App Design",
                "الموشن جرافيك",
                "Motion Graphics",
                "تحرير الفيديو",
                "Video Editing",
                "إنتاج المحتوى الإبداعي",
                "Creative Content Creation",
                "كتابة المحتوى الإعلاني",
                "Copywriting",
                "إدارة الحملات الإعلانية",
                "Ad Campaign Management",
                "إعلانات فيسبوك وانستجرام",
                "Facebook & Instagram Ads",
                "إعلانات جوجل",
                "Google Ads Specialist",
                "إعلانات تيك توك",
                "TikTok Ads",
                "إعلانات سناب شات",
                "Snapchat Ads Marketing",
                "تحليلات المواقع",
                "Google Analytics",
                "تحسين معدل التحويل",
                "Conversion Rate Optimization",
                "سيو محلي",
                "Local SEO",
                "سيو اليوتيوب",
                "YouTube SEO",
                "بناء العلامة التجارية",
                "Brand Strategy",
                "تصميم المطبوعات",
                "Print Design",
                "تصميم التغليف",
                "Packaging Design",
                "النمذجة الهندسية",
                "CAD Design",
                "تصميم ملفات STL",
                "3D Printing Design",
                "تصميم واجهات المستخدم",
                "User Interface Design",
                "الذكاء الاصطناعي في التصميم",
                "AI Design Tools",
                "التسويق عبر البريد الإلكتروني",
                "Email Marketing",
                "التسويق عبر المؤثرين",
                "Influencer Marketing",
                "إدارة السمعة الرقمية",
                "Online Reputation Management",
                "تحسين سرعة المواقع",
                "Website Speed Optimization",
                "أمن المواقع",
                "Cyber Security for Web",
                "تصميم العروض التقديمية",
                "Presentation Design",
                "تصميم الإنفوجرافيك",
                "Infographic Design",
                "تصميم الشعارات الخطية",
                "Typography & Calligraphy",
                "التسويق العقاري الرقمي",
                "Real Estate Digital Marketing",
                "التجارة الإلكترونية",
                "E-commerce Strategy",
                "الدروب شيبنج",
                "Dropshipping Business",
                "إدارة صفحات السوشيال ميديا",
                "Community Management",
                "تصميم البنرات الإعلانية",
                "Display Advertising Design",
                "تصوير المنتجات وتعديلها",
                "Product Image Retouching",
                "التحول الرقمي",
                "Digital Transformation",
                "تحليل المنافسين",
                "Competitor Analysis",
                "هندسة البحث",
                "Search Engine Marketing",
                "SEM",
                "تصميم المجلات والكتب",
                "Editorial Design",
                "الرسم الرقمي",
                "Digital Illustration",
                "تطوير الهوية المؤسسية",
                "Corporate Identity Design",
                "تصميم واجهات المتاجر",
                "Storefront Design",
                "ربط بوابات الدفع",
                "Payment Gateway Integration",
                "إدارة المشاريع الإبداعية",
                "Creative Project Management",
                "استراتيجيات النمو",
                "Growth Hacking",
                "إعلانات تويتر",
                "Twitter Ads",
                "إعلانات لينكد إن",
                "LinkedIn Ads Specialist",
                "تجهيز منصات سلة وزد",
                "Salla & Zid Platforms",
                "تصميم النماذج الأولية",
                "Prototyping",
                "تنسيق الألوان الفني",
                "Color Theory Application",
                "الإخراج الفني",
                "Art Direction",
              ],
              hasOfferCatalog: {
                "@type": "OfferCatalog",
                name: "خدمات ehabgm - ehabgm Services",
                itemListElement: [
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "تصميم المواقع - Web Design",
                      description:
                        "تصميم وتطوير مواقع احترافية متجاوبة | Professional Responsive Website Design & Development",
                      url: "https://ehabgm.com/website-design",
                    },
                  },
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "تصميم المتاجر الإلكترونية - E-commerce Design",
                      description:
                        "تصميم متاجر إلكترونية احترافية | Professional E-commerce Store Design & Development",
                      url: "https://ehabgm.com/ecommerce",
                    },
                  },
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "تصميم الجرافيك - Graphic Design",
                      description: "تصميم جرافيك احترافي وهوية بصرية | Professional Graphic Design & Visual Identity",
                      url: "https://ehabgm.com/brand-identity",
                    },
                  },
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "الإعلانات الممولة - Paid Advertising",
                      description:
                        "إدارة حملات إعلانية ممولة | Paid Ads Campaign Management (Facebook, Google, TikTok)",
                      url: "https://ehabgm.com/paid-ads",
                    },
                  },
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "إدارة السوشيال ميديا - Social Media Management",
                      description: "إدارة حسابات التواصل الاجتماعي | Professional Social Media Account Management",
                      url: "https://ehabgm.com/social-media",
                    },
                  },
                  {
                    "@type": "Offer",
                    itemOffered: {
                      "@type": "Service",
                      name: "تحسين محركات البحث - SEO",
                      description: "تحسين ترتيب موقعك في نتائج البحث | Search Engine Optimization Services",
                      url: "https://ehabgm.com/seo",
                    },
                  },
                ],
              },
            }),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "Person",
              "@id": "https://ehabgm.com/#person",
              name: "إيهاب محمد",
              alternateName: ["Ehab Mohamed", "ايهاب محمد", "ehabgm", "إيهاب جى ام", "Ehab Graphic"],
              jobTitle: "مصمم مواقع ومتاجر | مصمم جرافيك | خبير تسويق رقمي",
              description:
                "مصمم مواقع ومتاجر إلكترونية محترف ومصمم جرافيك مستقل وخبير في التسويق الرقمي والإعلانات الممولة | Professional Freelance Web Designer, Graphic Designer & Digital Marketing Expert",
              url: "https://ehabgm.com",
              image: "https://i.postimg.cc/TYyK2Rtv/logo.png",
              telephone: "+201022679250",
              email: "info@ehabgm.com",
              sameAs: [
                "https://ehabgm.com",
                "https://facebook.com/ehab.gm1",
                "https://instagram.com/ehabgm",
                "https://twitter.com/ehabgm",
                "https://linkedin.com/in/ehabgm",
              ],
              worksFor: {
                "@type": "Organization",
                name: "ehabgm",
                url: "https://ehabgm.com",
              },
              knowsAbout: [
                "Web Design",
                "Website Development",
                "E-commerce Development",
                "Graphic Design",
                "Logo Design",
                "Brand Identity Design",
                "Digital Marketing",
                "Social Media Marketing",
                "Paid Advertising",
                "SEO",
                "Facebook Ads",
                "Google Ads",
                "TikTok Ads",
                "Content Marketing",
                "تصميم مواقع",
                "تصميم متاجر",
                "تصميم جرافيك",
                "تصميم شعارات",
                "هوية بصرية",
                "تسويق رقمي",
                "إعلانات ممولة",
                "UI/UX Design",
                "User Experience Design",
                "User Interface Design",
                "WordPress Development",
                "Shopify Store Setup",
                "Salla Platform Expert",
                "Zid Platform Expert",
                "Landing Page Optimization",
                "Search Engine Optimization",
                "Search Engine Marketing",
                "Social Media Management",
                "Instagram Marketing",
                "Snapchat Ads",
                "LinkedIn Ads",
                "YouTube Marketing",
                "Email Marketing",
                "Conversion Rate Optimization",
                "CRO Specialist",
                "Copywriting",
                "Creative Writing",
                "Motion Graphics",
                "Video Editing",
                "3D Modeling",
                "3D Rendering",
                "CAD Design",
                "Product Design",
                "Packaging Design",
                "Print Design",
                "Typography",
                "Color Theory",
                "Brand Strategy",
                "Digital Branding",
                "Lead Generation",
                "Sales Funnel Design",
                "Market Research",
                "Competitor Analysis",
                "Mobile App Design",
                "Responsive Web Design",
                "Website Speed Optimization",
                "On-Page SEO",
                "Off-Page SEO",
                "Technical SEO",
                "Local SEO",
                "Backlink Strategy",
                "Google Analytics 4",
                "Google Tag Manager",
                "Meta Pixel Setup",
                "Marketing Automation",
                "Re-marketing Strategies",
                "Influencer Marketing",
                "Online Reputation Management",
                "Cyber Security for Websites",
                "SSL Certification",
                "API Integration",
                "Payment Gateway Setup",
                "Dropshipping Business",
                "Print on Demand",
                "Infographic Design",
                "Business Card Design",
                "Company Profile Design",
                "Social Media Post Design",
                "Ad Creative Design",
                "Thumbnail Design",
                "Vector Illustration",
                "Icon Design",
                "App Store Optimization",
                "ASO",
                "PPC Campaign Management",
                "Display Advertising",
                "Native Advertising",
                "WhatsApp Marketing",
                "Telegram Marketing",
                "SMS Marketing",
                "CRM Management",
                "Public Relations",
                "Event Branding",
                "Exhibition Stand Design",
                "Signage Design",
                "Outdoor Advertising",
                "Interior 3D Design",
                "Exterior 3D Design",
                "Architectural Visualization",
                "تصميم واجهات المستخدم",
                "تصميم تجربة المستخدم",
                "تطوير ووردبريس",
                "إنشاء متاجر شوبيفاي",
                "خبير منصة سلة",
                "خبير منصة زد",
                "تحسين محركات البحث",
                "إدارة حسابات التواصل الاجتماعي",
                "تسويق عبر انستجرام",
                "إعلانات سناب شات",
                "إعلانات لينكد إن",
                "تسويق عبر اليوتيوب",
                "تسويق عبر البريد الإلكتروني",
                "تحسين معدل التحويل",
                "كتابة المحتوى الإعلاني",
                "مونتاج فيديو",
                "موشن جرافيك",
                "تصميم ثلاثي الأبعاد",
                "ريندر احترافي",
                "تصميم منتجات",
                "تصميم تغليف المنتجات",
                "تصميم مطبوعات",
                "استراتيجية العلامة التجارية",
                "بناء الهوية الرقمية",
                "جلب العملاء المحتملين",
                "تصميم قمع المبيعات",
                "تحليل السوق",
                "تحليل المنافسين",
                "تصميم تطبيقات الجوال",
                "تصميم مواقع متجاوبة",
                "تحسين سرعة الموقع",
                "سيو داخلي",
                "سيو خارجي",
                "سيو تقني",
                "سيو محلي",
                "استراتيجيات الروابط الخلفية",
                "تحليلات جوجل",
                "إعداد بيكسل ميتا",
                "أتمتة التسويق",
                "إعادة الاستهداف",
                "التسويق عبر المؤثرين",
                "إدارة السمعة على الإنترنت",
                "حماية المواقع",
                "ربط بوابات الدفع",
                "دروبشيبينغ",
                "الطباعة عند الطلب",
                "تصميم إنفوجرافيك",
                "تصميم كروت شخصية",
                "تصميم بروفايل الشركات",
                "تصميم بوستات السوشيال ميديا",
                "تصميم إعلانات إبداعية",
                "تصميم صور مصغرة",
                "رسم فيكتور",
                "تصميم أيقونات",
                "تحسين متجر التطبيقات",
                "إدارة حملات الدفع مقابل النقرة",
                "الإعلانات الصورية",
                "تسويق عبر الواتساب",
                "تسويق عبر التيليجرام",
                "إدارة علاقات العملاء",
                "تنسيق المعارض",
                "تصميم اللوحات الإعلانية",
                "تصميم 3D خارجي",
                "تصميم 3D داخلي",
                "إخراج معماري",
                "هندسة العلامة التجارية",
                "Digital Strategy",
                "استراتيجية رقمية",
                "Content Strategy",
                "استراتيجية المحتوى",
                "Web Analytics",
                "تحليل الويب",
                "Visual Identity",
                "الهوية المرئية",
                "Corporate Branding",
                "هوية المؤسسات",
                "Startup Branding",
                "هوية الشركات الناشئة",
                "E-book Design",
                "تصميم الكتب الإلكترونية",
                "Whitepaper Design",
                "تصميم الأوراق البحثية",
                "PowerPoint Design",
                "تصميم العروض التقديمية",
                "Growth Hacking",
                "اختراق النمو",
                "Affiliate Marketing",
                "التسويق بالعمولة",
                "Influencer Outreach",
                "الوصول للمؤثرين",
                "Online Course Design",
                "تصميم الدورات عبر الإنترنت",
                "LMS Development",
                "تطوير منصات التعليم",
                "Customer Journey Mapping",
                "رسم رحلة العميل",
                "E-commerce SEO",
                "سيو المتاجر الإلكترونية",
                "Video Marketing",
                "التسويق بالفيديو",
                "Storyboarding",
                "رسم السيناريو",
                "Photo Editing",
                "تعديل الصور",
                "Retouching",
                "معالجة الصور",
                "Vector Tracing",
                "تحويل الصور لفيكتور",
                "Print Management",
                "إدارة الطباعة",
                "Bulk SMS Marketing",
                "تسويق الرسائل القصيرة",
                "Domain Management",
                "إدارة النطاقات",
                "Hosting Setup",
                "إعداد الاستضافة"
              ],
              hasOccupation: [
                {
                  "@type": "Occupation",
                  name: "Web Designer",
                  alternateName: "مصمم مواقع",
                },
                {
                  "@type": "Occupation",
                  name: "Graphic Designer",
                  alternateName: "مصمم جرافيك",
                },
                {
                  "@type": "Occupation",
                  name: "Digital Marketing Specialist",
                  alternateName: "متخصص تسويق رقمي",
                },
              ],
            }),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "WebSite",
              "@id": "https://ehabgm.com/#website",
              name: "ehabgm - إيهاب جى ام",
              alternateName: ["ehabgm", "إيهاب جى ام", "Ehab Graphic", "ehabgm Digital Marketing", "مصمم مواقع ايهاب"],
              url: "https://ehabgm.com",
              publisher: {
                "@id": "https://ehabgm.com/#organization",
              },
              inLanguage: ["ar", "en"],
              potentialAction: {
                "@type": "SearchAction",
                target: {
                  "@type": "EntryPoint",
                  urlTemplate: "https://ehabgm.com/search?q={search_term_string}",
                },
                "query-input": "required name=search_term_string",
              },
            }),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "BreadcrumbList",
              itemListElement: [
                {
                  "@type": "ListItem",
                  position: 1,
                  name: "الرئيسية - Home",
                  item: "https://ehabgm.com",
                },
              ],
            }),
          }}
        />
        <script
          type="application/ld+json"
          dangerouslySetInnerHTML={{
            __html: JSON.stringify({
              "@context": "https://schema.org",
              "@type": "FAQPage",
              mainEntity: [
                {
                  "@type": "Question",
                  name: "من هو ايهاب جى ام؟ Who is ehabgm?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "إيهاب جى ام (ehabgm) هو مصمم مواقع ومتاجر إلكترونية محترف ومصمم جرافيك مستقل من حلوان, وخبير في التسويق الرقمي والإعلانات الممولة في مصر. ehabgm is a professional freelance web designer, graphic designer, and digital marketing expert based in Egypt.",
                  },
                },
                {
                  "@type": "Question",
                  name: "ما هي خدمات ehabgm؟ What services does ehabgm offer?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "يقدم ايهاب خدمات تصميم المواقع، تصميم المتاجر الإلكترونية، تصميم الجرافيك والهوية البصرية، إدارة السوشيال ميديا، الإعلانات الممولة، وتحسين محركات البحث SEO. We offer web design, e-commerce development, graphic design, brand identity, social media management, paid advertising, and SEO services.",
                  },
                },
                {
                  "@type": "Question",
                  name: "كيف أتواصل مع ايهاب جى ام؟ How to contact ehabgm?",
                  acceptedAnswer: {
                    "@type": "Answer",
                    text: "يمكنك التواصل معنا عبر الواتساب على الرقم  01140057253 ,01022679250 أو زيارة موقعنا ehabgm.com. Contact us via WhatsApp at +201022679250 or visit ehabgm.com",
                  },
                },
              ],
            }),
          }}
        />
      </head>
      <body className="arabic-text">
        <ClientComponents />
        <SiteHeader />
        <main className="pt-16">{children}</main>
        <Footer />
        <AnimatedBackground />
        <ThemeToggle />
        <AccessibilityMenu />
        <SmartNotifications />
        <PerformanceMonitor />
        <a
          href="https://wa.me/201022679250"
          className="fixed bottom-20 left-4 z-40 bg-green-500 text-white p-3 sm:p-4 rounded-full shadow-lg hover:bg-green-600 transition-colors touch-manipulation active:scale-95"
          aria-label="تواصل عبر الواتساب - Contact via WhatsApp"
        >
          <svg className="w-5 h-5 sm:w-6 sm:h-6" fill="currentColor" viewBox="0 0 24 24">
            <path d="M17.472 14.382c-.297-.149-1.758-.867-2.03-.967-.273-.099-.471-.148-.67.15-.197.297-.767.966-.94 1.164-.173.199-.347.223-.644.075-.297-.15-1.255-.463-2.39-1.475-.883-.788-1.48-1.761-1.653-2.059-.173-.297-.018-.458.13-.606.134-.133.298-.347.446-.52.149-.174.198-.298.298-.497.099-.198.05-.371-.025-.52-.075-.149-.669-1.612-.916-2.207-.242-.579-.487-.5-.669-.51-.173-.008-.371-.01-.57-.01-.198 0-.52.074-.792.372-.272.297-1.04 1.016-1.04 2.479 0 1.462 1.065 2.875 1.213 3.074.149.198 2.096 3.2 5.077 4.487.709.306 1.262.489 1.694.625.712.227 1.36.195 1.871.118.571-.085 1.758-.719 2.006-1.413.248-.694.248-1.289.173-1.413-.074-.124-.272-.198-.57-.347m-5.421 7.403h-.004a9.87 9.87 0 01-5.031-1.378l-.361-.214-3.741.982.998-3.648-.235-.374a9.86 9.86 0 01-1.51-5.26c.001-5.45 4.436-9.884 9.888-9.884 2.64 0 5.122 1.03 6.988 2.898a9.825 9.825 0 012.893 6.994c-.003 5.45-4.437 9.884-9.885 9.884m8.413-18.297A11.815 11.815 0 0012.05 0C5.495 0 .16 5.335.157 11.892c0 2.096.547 4.142 1.588 5.945L.057 24l6.305-1.654a11.882 11.882 0 005.683 1.448h.005c6.554 0 11.89-5.335 11.893-11.893A11.821 11.821 0 0020.885 3.488" />
          </svg>
        </a>
      </body>
    </html>
  )
}
