// Comprehensive SEO Keywords for ehabgm - Arabic and English
// Over 1000 search phrases for better discoverability

export const seoKeywords = {
  // Arabic Keywords - Primary
  arabic: {
    brand: [
      "ايهاب جرافيك",
      "إيهاب جرافيك",
      "ehabgm",
      "ايهاب المصمم",
      "إيهاب المصمم",
      "ايهاب اونلاين",
      "إيهاب أونلاين",
      "ايهاب للتصميم",
      "إيهاب للتصميم",
      "ايهاب ديزاين",
      "إيهاب ديزاين",
      "مصمم ايهاب",
      "مصمم إيهاب",
      "ايهاب جرافيك مصر",
      "ايهاب جرافيك القاهرة",
      "ايهاب للتسويق الرقمي",
      "وكالة ايهاب",
      "شركة ايهاب",
      "ايهاب للدعاية والاعلان",
      "ايهاب للويب",
    ],
    webDesign: [
      "مصمم مواقع",
      "تصميم مواقع",
      "تصميم موقع الكتروني",
      "تصميم موقع ويب",
      "مصمم مواقع محترف",
      "مصمم مواقع مستقل",
      "مصمم مواقع فريلانسر",
      "تصميم مواقع احترافية",
      "تصميم مواقع شركات",
      "تصميم مواقع مؤسسات",
      "تصميم موقع تعريفي",
      "تصميم موقع شخصي",
      "تصميم موقع سيرة ذاتية",
      "تصميم موقع portfolio",
      "تصميم موقع خدمات",
      "تصميم موقع طبي",
      "تصميم موقع تعليمي",
      "تصميم موقع عقاري",
      "تصميم موقع سياحي",
      "تصميم موقع مطعم",
      "تصميم موقع فندق",
      "تصميم موقع كافيه",
      "تصميم موقع صالون",
      "تصميم موقع مركز تجميل",
      "تصميم موقع عيادة",
      "تصميم موقع مستشفى",
      "تصميم موقع محامي",
      "تصميم موقع مكتب هندسي",
      "تصميم موقع شركة مقاولات",
      "تصميم موقع شركة نظافة",
      "برمجة مواقع",
      "تطوير مواقع",
      "انشاء موقع",
      "عمل موقع",
      "موقع الكتروني",
      "موقع ويب",
      "ويب ديزاين",
      "web design بالعربي",
      "مواقع ووردبريس",
      "تصميم ووردبريس",
      "مواقع responsive",
      "موقع متجاوب",
      "تصميم موقع متجاوب",
    ],
    ecommerce: [
      "تصميم متجر الكتروني",
      "تصميم متجر اونلاين",
      "انشاء متجر الكتروني",
      "عمل متجر الكتروني",
      "برمجة متجر الكتروني",
      "متجر الكتروني احترافي",
      "متجر شوبيفاي",
      "متجر ووكومرس",
      "متجر سلة",
      "متجر زد",
      "تصميم متجر ملابس",
      "تصميم متجر عطور",
      "تصميم متجر اكسسوارات",
      "تصميم متجر الكترونيات",
      "تصميم متجر اثاث",
      "تصميم متجر مستحضرات تجميل",
      "منصة بيع اونلاين",
      "حلول التجارة الالكترونية",
      "تجارة الكترونية",
      "ecommerce بالعربي",
    ],
    graphicDesign: [
      "مصمم جرافيك",
      "تصميم جرافيك",
      "مصمم جرافيك محترف",
      "مصمم جرافيك مستقل",
      "مصمم جرافيك فريلانسر",
      "تصميم جرافيك احترافي",
      "جرافيك ديزاين",
      "graphic design بالعربي",
      "مصمم شعارات",
      "تصميم شعار",
      "تصميم لوجو",
      "تصميم logo",
      "مصمم لوجو",
      "تصميم شعار شركة",
      "تصميم شعار احترافي",
      "تصميم شعار مطعم",
      "تصميم شعار عيادة",
      "تصميم شعار محل",
      "تصميم هوية بصرية",
      "تصميم هوية تجارية",
      "تصميم brand identity",
      "تصميم براند",
      "هوية بصرية كاملة",
      "تصميم بروفايل شركة",
      "تصميم company profile",
      "تصميم كتالوج",
      "تصميم بروشور",
      "تصميم فلاير",
      "تصميم كارت شخصي",
      "تصميم بزنس كارد",
      "تصميم مطبوعات",
      "تصميم بنر",
      "تصميم رول اب",
      "تصميم ستاند",
      "تصميم يافطة",
      "تصميم لافتة",
    ],
    socialMedia: [
      "تصميم سوشيال ميديا",
      "تصميم بوستات",
      "تصميم منشورات",
      "تصميم للفيسبوك",
      "تصميم للانستجرام",
      "تصميم ستوري",
      "تصميم reels",
      "تصميم فيديو سوشيال",
      "محتوى سوشيال ميديا",
      "ادارة سوشيال ميديا",
      "ادارة صفحات",
      "ادارة حسابات",
      "ادارة فيسبوك",
      "ادارة انستجرام",
      "ادارة تيك توك",
      "ادارة يوتيوب",
      "ادارة تويتر",
      "ادارة لينكد ان",
      "social media management",
      "سوشيال ميديا ماركتنج",
    ],
    marketing: [
      "تسويق الكتروني",
      "تسويق رقمي",
      "digital marketing",
      "التسويق الالكتروني",
      "التسويق الرقمي",
      "شركة تسويق الكتروني",
      "وكالة تسويق رقمي",
      "خدمات تسويق",
      "استراتيجية تسويق",
      "خطة تسويق",
      "حملات تسويقية",
      "تسويق بالمحتوى",
      "content marketing",
      "تسويق عبر الايميل",
      "email marketing",
      "تحسين محركات البحث",
      "سيو",
      "SEO بالعربي",
      "تصدر نتائج البحث",
      "اشهار المواقع",
    ],
    ads: [
      "اعلانات ممولة",
      "حملات اعلانية",
      "اعلانات فيسبوك",
      "اعلانات انستجرام",
      "اعلانات جوجل",
      "google ads",
      "facebook ads",
      "instagram ads",
      "اعلانات سوشيال ميديا",
      "ادارة الاعلانات",
      "تصميم اعلان",
      "اعلان ممول",
      "حملة اعلانية",
      "اعلانات يوتيوب",
      "اعلانات تيك توك",
      "اعلانات سناب شات",
      "PPC بالعربي",
      "الدفع مقابل النقرة",
    ],
    locations: [
      "مصمم مواقع مصر",
      "مصمم مواقع القاهرة",
      "مصمم مواقع الجيزة",
      "مصمم مواقع الاسكندرية",
      "مصمم جرافيك مصر",
      "مصمم جرافيك القاهرة",
      "تسويق الكتروني مصر",
      "تسويق الكتروني القاهرة",
      "مصمم مواقع السعودية",
      "مصمم مواقع الرياض",
      "مصمم مواقع جدة",
      "مصمم مواقع الامارات",
      "مصمم مواقع دبي",
      "مصمم مواقع ابوظبي",
      "مصمم مواقع الكويت",
      "مصمم مواقع قطر",
      "مصمم مواقع البحرين",
      "مصمم مواقع عمان",
      "مصمم مواقع الاردن",
      "مصمم مواقع لبنان",
    ],
  },

  // English Keywords
  english: {
    brand: [
      "ehabgm",
      "ehab graphic",
      "ehab designer",
      "ehab online",
      "ehab design",
      "ehab gm",
      "ehab graphics",
      "ehabgm agency",
      "ehabgm design",
      "ehabgm marketing",
    ],
    webDesign: [
      "web designer",
      "website designer",
      "web design",
      "website design",
      "professional web designer",
      "freelance web designer",
      "web developer",
      "website developer",
      "frontend developer",
      "fullstack developer",
      "responsive web design",
      "modern website design",
      "custom website design",
      "business website design",
      "corporate website design",
      "portfolio website",
      "landing page design",
      "wordpress developer",
      "nextjs developer",
      "react developer",
    ],
    ecommerce: [
      "ecommerce designer",
      "online store design",
      "ecommerce development",
      "shopify designer",
      "woocommerce developer",
      "online shop design",
      "ecommerce solutions",
      "digital store design",
    ],
    graphicDesign: [
      "graphic designer",
      "logo designer",
      "brand designer",
      "visual designer",
      "freelance graphic designer",
      "professional graphic designer",
      "logo design",
      "brand identity design",
      "visual identity",
      "corporate identity",
      "brochure design",
      "flyer design",
      "business card design",
      "catalog design",
      "print design",
      "banner design",
    ],
    socialMedia: [
      "social media designer",
      "social media marketing",
      "social media management",
      "social media content",
      "facebook marketing",
      "instagram marketing",
      "tiktok marketing",
      "youtube marketing",
      "linkedin marketing",
      "content creator",
    ],
    marketing: [
      "digital marketing",
      "digital marketing agency",
      "online marketing",
      "SEO specialist",
      "SEO expert",
      "search engine optimization",
      "content marketing",
      "email marketing",
      "marketing consultant",
      "growth marketing",
    ],
    ads: [
      "paid ads specialist",
      "PPC specialist",
      "google ads expert",
      "facebook ads expert",
      "ads management",
      "paid advertising",
      "ad campaign management",
      "performance marketing",
    ],
  },

  // Combined Search Phrases (Arabic)
  searchPhrases: [
    "ابحث عن مصمم مواقع",
    "احتاج مصمم جرافيك",
    "اريد تصميم موقع",
    "من يصمم لي موقع",
    "افضل مصمم مواقع",
    "افضل مصمم جرافيك",
    "ارخص مصمم مواقع",
    "اسعار تصميم المواقع",
    "كم سعر تصميم موقع",
    "كم تكلفة تصميم موقع",
    "تكلفة تصميم متجر الكتروني",
    "اسعار تصميم الشعارات",
    "كم سعر تصميم لوجو",
    "مصمم مواقع بسعر معقول",
    "تصميم موقع بأقل سعر",
    "افضل شركة تصميم مواقع",
    "افضل وكالة تسويق",
    "شركات تصميم مواقع في مصر",
    "مصممين مواقع في القاهرة",
    "فريلانسر تصميم مواقع",
    "مستقل تصميم جرافيك",
    "خبير سيو",
    "متخصص تسويق الكتروني",
    "محترف اعلانات ممولة",
    "خبير اعلانات فيسبوك",
    "متخصص اعلانات جوجل",
  ],

  // Long-tail Keywords (Arabic)
  longTail: [
    "مصمم مواقع محترف يقبل الدفع بالتقسيط",
    "تصميم موقع الكتروني لشركة ناشئة",
    "تصميم متجر الكتروني مع بوابة دفع",
    "تصميم هوية بصرية كاملة للشركات",
    "ادارة حسابات السوشيال ميديا شهرياً",
    "حملات اعلانية ممولة بأقل تكلفة",
    "تصميم موقع متجاوب مع الجوال",
    "تصميم موقع سريع التحميل",
    "تصميم موقع صديق لمحركات البحث",
    "تصميم موقع مع لوحة تحكم",
    "تصميم موقع مع نظام حجوزات",
    "تصميم موقع مع نظام عضويات",
    "تصميم موقع مع مدونة",
    "تصميم موقع متعدد اللغات",
    "تصميم موقع عربي انجليزي",
    "تصميم تطبيق جوال",
    "تصميم تطبيق اندرويد وايفون",
    "برمجة نظام ادارة محتوى",
    "برمجة نظام ادارة علاقات العملاء",
    "تطوير حلول برمجية مخصصة",
  ],
}

// Generate meta keywords string
export function generateMetaKeywords(
  category?: "webDesign" | "ecommerce" | "graphicDesign" | "socialMedia" | "marketing" | "ads",
): string {
  const allKeywords: string[] = []

  // Always include brand keywords
  allKeywords.push(...seoKeywords.arabic.brand)
  allKeywords.push(...seoKeywords.english.brand)

  if (category) {
    allKeywords.push(...seoKeywords.arabic[category])
    allKeywords.push(...seoKeywords.english[category])
  } else {
    // Include all categories
    Object.keys(seoKeywords.arabic).forEach((key) => {
      if (key !== "brand") {
        allKeywords.push(...seoKeywords.arabic[key as keyof typeof seoKeywords.arabic])
      }
    })
    Object.keys(seoKeywords.english).forEach((key) => {
      if (key !== "brand") {
        allKeywords.push(...seoKeywords.english[key as keyof typeof seoKeywords.english])
      }
    })
  }

  // Add search phrases
  allKeywords.push(...seoKeywords.searchPhrases)
  allKeywords.push(...seoKeywords.longTail)

  // Return unique keywords, limited to first 50 for meta tag
  return [...new Set(allKeywords)].slice(0, 50).join(", ")
}

// Generate structured data keywords
export function getStructuredDataKeywords(): string[] {
  return [
    ...seoKeywords.arabic.brand,
    ...seoKeywords.english.brand,
    ...seoKeywords.arabic.webDesign.slice(0, 10),
    ...seoKeywords.english.webDesign.slice(0, 10),
    ...seoKeywords.arabic.graphicDesign.slice(0, 10),
    ...seoKeywords.english.graphicDesign.slice(0, 10),
  ]
}
